---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab02-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/lab02
    server: 172.22.2.230

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab02-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
