---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab04-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/lab04
    server: 172.22.2.230

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab04-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
