---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab03-tmp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/lab03/tmp
    server: 172.22.2.230
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab03-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/lab03/data
    server: 172.22.2.230

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab03-tmp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab03-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
