apiVersion: batch/v1
kind: Job
metadata:
  name: worker1
spec:
  template:
    metadata:
      labels:
        app: worker1
        role: worker
    spec:
      containers:
      - name: worker1
        image: tensorflow/tensorflow:1.0.1
        ports:
        - containerPort: 2222
        env:
        - name: PS_HOSTS
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ps
        - name: WORKER_HOSTS
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: worker
        command: ["/bin/sh", "-c"]
        args: ["
            curl https://gist.githubusercontent.com/kairen/17da73517ae6a2dca9df578d4b3adef0/raw/6ca3d7b15cf3dde5ab321ef43c4635b2d494a1a1/cancer_classifier.py -o /opt/cancer_classifier.py;
            python /opt/cancer_classifier.py \
                   --ps_hosts=$(PS_HOSTS) \
                   --worker_hosts=$(WORKER_HOSTS) \
                   --job_name=worker \
                   --task_index=1 \
                   --log_path=/tmp/train \
                   --data_dir=/data ;
            echo 'Train done...';"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp/train
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lab03-data-pvc
        - name: tmp
          persistentVolumeClaim:
            claimName: lab03-tmp-pvc
      nodeName: kube-node3

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tf-worker1-service
  name: worker1
spec:
  selector:
    app: worker1
  ports:
  - port: 2222
    targetPort: 2222
