apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker0
        role: worker
    spec:
      containers:
      - name: worker0
        image: tensorflow/tensorflow:1.0.1
        ports:
        - containerPort: 2222
        env:
        - name: PS_HOSTS
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ps
        - name: WORKER_HOSTS
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: worker
        command: ["/bin/sh", "-c"]
        args: ["
            curl https://gist.githubusercontent.com/kairen/169bd3faccbb5298ef318e2295d5aa99/raw/d1febdcf0d2e9fdd228cf14cc1914351eede27ce/cancer_classifier.py -o /opt/cancer_classifier.py;
            python /opt/cancer_classifier.py \
                   --ps_hosts=$(PS_HOSTS) \
                   --worker_hosts=$(WORKER_HOSTS) \
                   --job_name=worker \
                   --task_index=0 \
                   --log_path=/tmp/train \
                   --data_dir=/data ;
            echo 'Train done...';
            while :; do sleep 2; done ;"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp/train
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lab03-data-pvc
        - name: tmp
          persistentVolumeClaim:
            claimName: lab03-tmp-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tf-worker0-service
  name: worker0
spec:
  selector:
    app: worker0
  ports:
  - port: 2222
    targetPort: 2222
